### ISSUE TITLE
Cookie banner hides footer

### ISSUE THREAD

**Issue by luckydonald** [danog-clients/legacy#12]
The text "Contattare Daniil Gentili se si riscontrano problemi con il sito." is not fully visible.
Whatever that means, I don't speak italics 😝

<img width="1299" alt="Screenshot 2020-01-06 at 19 19 59" src="https://user-images.githubusercontent.com/2737108/71838632-97acf900-30b9-11ea-8cbb-952a1466e5ad.png">

**Comment by danog** [comment]
topkek, ye I my new websites are better xd
